### ISSUE TITLE
Iteration Plan for February 2019

### ISSUE THREAD

**Issue by patniko** [Microsoft/appcenter#1]
# February 2019 Plan
Kicking off the month of February is work to reduce confusion around billing within App Center's portal. We'll surface more usage information and ease some friction experienced managing your connected subscriptions. Supporting the HockeyApp community while they make the switch to App Center continues to be a strong focus of ours with more key features planned to ship this month.

We're kicking off an initiative to improve your experience working with backend technologies by overhauling our Push service and introducing multiple new services throughout the year. We'll begin sharing designs and mockups for some of the services this iteration to garner early feedback and help you drive the direction of the services towards the future.

Below is a summary of the top level plan items covering the February, 2019 time period. 

### Billing
- [x] Expose billing endpoints in public API [#5]
- [x] Make it easier to remove/change Azure subscriptions from your account [#6]
- [ ] ~~Make it easier to discover organization billing options~~ [#7]
- [ ] ~~Display Billing History for services~~ [#8]

### Distribution
- [ ] ~~Release to individual testers and multiple distribution groups~~ [#10]

### Diagnostics
- [x] Search for crashes by an user identifier [#4]
- [ ] ~~Integration with Playfab Game Manager console~~ [#2]
- [ ] ~~Filter crash and error groups by build number~~ [#55]

### Identity
- [x] Create initial designs for the new identity solution [#11]

### Push
- [X] Indicate when audiences exceed the existing 1,000 devices limit [#3]
- [ ] ~~Remove billing plan options, App Center Push becomes a free service~~ [#9] 

### Storage
- [x] Create initial designs for the new data solution [#14]

### Test
- [x] Support for Appium 1.11

## Security
- [x] Deprecation of TLS 1.0 and TLS 1.1 connectivity in favor or TLS 1.2 [#36]

## Proposals
- [x] Improving App Center access controls [#13]

**Comment by patniko** [comment]
# Key developments
- We improved the way you can manage your Azure subscription in App Center and exposed billing api's
- Missing HockeyApp features were added to diagnostics and distribution services
- The HockeyApp to App Center transition experience is currently under development with details to be shared in the near future
- Development started on the Identity and Data Sync SDK, API and web portal services
- Public plans were shared for new services and improving security options

# Completed 

- [x] Expose billing endpoints in public API [#5]
- [x] Make it easier to remove/change Azure subscriptions from your account [#6]
- [x] Search for crashes by an user identifier [#4]
- [x] Create initial designs for the new identity solution [#11]
- [X] Indicate when audiences exceed the existing 1,000 devices limit [#3]
- [x] Create initial designs for the new data solution [#14]
- [x] Support for Appium 1.11
- [x] Deprecation of TLS 1.0 and TLS 1.1 connectivity in favor or TLS 1.2 [#36]
- [x] Improving App Center access controls [#13]

# Reprioritized
5 of the 15 items on February's plan are currently in progress and will be carried over to the March iteration plan for completion. 
- [ ] Make it easier to discover organization billing options [#7]

- [ ] Release to individual testers and multiple distribution groups [#10]
- [ ] Integration with Playfab Game Manager console [#2]
- [ ] Filter crash and error groups by build number [#55]
- [ ] Remove billing plan options, App Center Push becomes a free service [#9] 


# Deferred
We'll be deferring 1 item until a later time. Given our current workload we don't plan to address this item next month.
- Display Billing History for services [#8]
