### ISSUE TITLE
Iteration Plan for March 2019

### ISSUE THREAD

**Issue by patniko** [Microsoft/appcenter#107]
# March 2019 Plan 
This month keeps the same themes around HockeyApp shutdown readiness, general improvements and new developer backend services from our [last iteration plan](https://github.com/Microsoft/appcenter/issues/1#issuecomment-468114566). We'll continue to share technical designs and UI mockups for our new Identity and Storage backend services while working on the public preview over the coming months.

For HockeyApp users interested in adopting App Center, we'll be adding in general improvements across distribution and diagnostics services while continuing work on the new migration experience. If you're using HockeyApp and feel there is a feature critical to you missing from App Center don't hesitate to create an issue so we can triage your needs right away.

A key addition to this plan are a few user submissions of your own. We recognize the interest  @SandroMachado's request #22 has received and will be working on and sharing a feature spec this month for review. A few small requests were added to the plan as well to address minor papercuts such as being able to download mobile releases in our install portal from your desktop web browser. 

Below is a detailed summary of the top level plan items covering the March, 2019 time period. 

### General
- [ ] ~~Add support to indicate the environment or release type of an app~~ [#120]

### Billing
- [ ] ~~Make it easier to understand personal and organization level billing~~ [#7] 

### Build
- [x] Specification for cloning branch configuration [#106] (@SandroMachado #22)
- [ ] Support for building apps with Xcode 10.2 on macOS Mojave. All builds using Xcode 9.4.1 or above will begin building on macOS Mojave

### Diagnostics
- [x] Integration with Playfab Game Manager console [#2]
- [ ] ~~Filter crash and error groups by build number~~ [#133]

### Distribution
- [x] Download releases from install portal on unsupported platform [#82] (@UnreachableCode)
- [ ] ~~Disable in-app update when in guided access mode [#46] (@florianbuerger)~~
- [x] Release to individual testers and multiple distribution groups [#10]
- [x] Disable releases [#121]
- [x] Silent notifications when releasing [#122]
- [ ] ~~CodePush support for Electron apps~~

### Identity
- [ ] ~~Create a new or configure an existing AD B2C directory in App Center~~ [#113]
- [x] Sign-in and out experience to authenticate users of your app [#114]

### Push
- [x] Remove billing plan options [#9] 
- [x] Push by user id mockups [#15]

### Storage 
- [x] Iterate on design and and share preview release mockups [#14]

### Test
- [ ] ~~NUnit 3 support~~ [#123]

**Comment by ericloeliger** [comment]
@patniko Is there a plan in the roadmap to integrate App Center directly into Azure DevOps?  Or will they remain as separate tools? Even if this is many months out, just curious if it is planned.

**Comment by patniko** [comment]
No direct plans @ericloeliger. HockeyApp shutdown and service enhancements are our top priority, but you'll continue to see DevOps and App Center align from a style perspective as our design team is shared across both services.

**Comment by lfkwtz** [comment]
any ETA for xcode 10.2?

**Comment by lumaxis** [comment]
@lfkwtz We're already working on it, so it shouldn't be too long anymore 🙏🏼

**Comment by andrewtechhelp** [comment]
With the NUnit 3 support for Xamarin.UITest being crossed out here and not listed on the April 2019 Iteration Plan, does this mean this item isn't going to be happening any time soon now?
