### ISSUE TITLE
Iteration Plan for October 2019

### ISSUE THREAD

**Issue by nrajpurkar** [microsoft/appcenter#1114]
# October 2019 Plan

All aboard the Xcode beta train as it pulls into the final GA station. We continually updated Build to support these versions for Swift/Obj-C and React Native apps and added stable support for Xamarin.iOS apps. Additionally, we shipped two major Build requests - building from self-hosted GitLab repos and support for Xamarin.iOS app extensions. You can now better see information related to your apps usage of Data with the Metrics view. We wrapped up work for macOS and iOS extension support in Diagnostics, and you can start using that with the October SDK release. We’re continuing to make transitioning from HockeyApp to App Center as smooth as possible with the ability to move multiple apps at once and manage your organizations directly in App Center.

October will continue to see additional features added to Auth. Data’s Metrics Explorer will get a boost with Traffic Maps. In addition to the macOS and iOS extension support in Diagnostics, there will be some additional features for Windows apps. Distribution will support Sparkle feeds and in-app updates through public distribution groups. Here’s to a productive month for all our app developers!

### Auth
- [ ] ~Support bringing your own identity management provider (Firebase Authentication and Auth0) with App Center Auth [#637]~
- [ ] ~Enable developers to connect their Active Azure Directory to Auth [#994]~

### Data
- [ ] ~Continue Free Tier investigatory work [#799]~
- [x] CRUD functionality in the Data Explorer  [#800]
- [ ] ~Traffic Map in Metrics Explorer [#660]~
- [ ] ~Engineering Design Work on Data Change Notifications [#1121]~

### Diagnostics
- [x] API to upload custom crashes [#31]
- [x] Support macOS & iOS extensions [#687]
- [x] Crashes and errors support for UWP apps [#752, #150, #403]
- [x]  User ID support for WPF, WinForms, and UWP apps
- [x] Search by exception type [#485 ]

### Distribution
- [x] Support Sparkle feeds for macOS/Windows in-app updates [#202]
- [x] In-app update through public distribution groups [#182]
- [ ] ~Externally hosted builds~
- [ ] ~Updated tester experience [#986, #140, #369, #176]~

### SDK
- [x] Add diagnostics (crashes) support for iOS extensions [#687]

### HockeyApp
- [x] Switch the distribution groups management for organizations to App Center

### General
- [ ] ~Custom apps platform support~
- [ ] ~Research for compute backend-as-a-service from App Center [#993]~

### Test
- [x] Add iOS 13 devices to the device selection
- [ ] ~Add iOS 13 and Xcode 11 support to Xamarin.UITest [#1129]~

**Comment by Zee-day** [comment]
Any news on #32 ?

**Comment by absinth70** [comment]
Is there some timeline for supporting In-App updates for .Net Core 3 WPF apps?

**Comment by dimazaid** [comment]
@absinth70 - we don't have timeline at the moment. Do you mind creating an issue and add your vote so we can track it?

**Comment by absinth70** [comment]
@dimazaid I think (and hope) its already covered by this one: #1228 (Enable In-app updates for WPF Applications (feature parity with HockeyApp)). Even I'm not able to find any functional Sparkle SDK for .Net core WPF :/

**Comment by martinarvaiaccedo** [comment]
I think Custom apps platform support equal to #464?

**Comment by rishimodha** [comment]
@nrajpurkar Are there any plans to support the Squirrel flag for the Sparkle update feed? This was supported on HockeyApp and it is required for Electron AutoUpdater, which does not support XML output and requires JSON. See example: https://rink.hockeyapp.net/api/2/apps/bc02347d258a40e2af46cc8de3566bab.json?squirrel=true

It won't be possible for us to complete the transition to AppCenter from HockeyApp until support for Squirrel JSON format is added. Please do not force a transition before this is supported as it will cut off our customer's ability to update their apps.

**Comment by lbrownell-gpsw** [comment]
Time for that November 2019 iteration plan...

**Comment by Oddj0b** [comment]
November plan is at #1322

**Comment by OzBob** [comment]
@rishimodha and anyone else looking for 'Squirrel flag for the Sparkle update feed' see #1304
