### ISSUE TITLE
Iteration Plan for November 2019

### ISSUE THREAD

**Issue by Oddj0b** [microsoft/appcenter#1322]
# November 2019 Plan
October was an excellent month for UWP developers with the release of Diagnostics support, and you can see which crashes your customers are experiencing with your apps. In November, we will continue work on bring-your-own-identify for our Auth service, and in our SDK, the work continues to support last month's support for iOS extensions.

### Auth
- [ ] Support bringing your own identity management provider (Firebase Authentication and Auth0) with App Center Auth [#637]
- [ ] Enable developers to connect their Active Azure Directory to Auth [#994]

### Data
- [ ] Continue Free Tier investigatory work [#799]
- [ ] Traffic Map in Metrics Explorer [#660]
- [ ] Engineering Design Work on Data Change Notifications [#1121] 

### Diagnostics
- [x] Handled exceptions support for Android [#827, #163 ]
- [x] Support deobfuscation for R8/D8 [#698, #458]
- [ ] Show unsymbolicated crashes and include in total counts [#110, #939 ]
- [x] Process .so files for NDK Crash symbolication [#1160]
- [ ] Manually upload crash logs in the UI [#289, #1317]

### Distribution
- [x] Externally hosted builds
- [ ] Updated tester experience #986, #140, #369, #1176 

### General
- [x] Custom apps platform support [#464]
- [ ] Research for compute backend-as-a-service from App Center [#993]
- [ ] Support Azure Active Directory security groups in App Center shared distribution groups

### Test
- [x] Add iOS 13 and Xcode 11 support to Xamarin.UITest [#1129]

**Comment by joshfriend** [comment]
Really hoping that #140 and related make it this time. HockeyApp will be dead **next week** and Appcenter is still missing this amazing feature that hockey offered for years.

**Comment by lbrownell-gpsw** [comment]
Custom apps platform support doesn't have an issue number, but it should include this: https://github.com/microsoft/appcenter/issues/464, and is one of the "we won't migrate your apps from HockeyApp on the 16th if they are affected by this" items.

**Comment by Oddj0b** [comment]
@lbrownell-gpsw thanks for the issue number, I've added it to the road-map.

**Comment by alfarahn** [comment]
Happy to see the handled exceptions on the RoadMap thanks for this @Oddj0b @winnieli1

**Comment by Fab1n** [comment]
What about thread names? In HockeyApp thread names for Apple platforms were displayed. 
This is missing, too.

All in all, I must honestly say, we are still very disappointed about the feature set compared to HockeyApp.
The only problem is that you are shutting down HockeyApp while still some key features are missing. 

If the shutdown would happen while most features were implemented, this wouldn't be that much of a problem.

The things that are really hurting (because missing) when HockeyApp shuts down:
1. Cannot upload (Apple) crash reports manually (https://openapi.appcenter.ms/#/crash/textError_upload doesn't work - reports don't show up)
2. The crash log are really bad to read
    - The logs are too bulky
    - The logs should instead be more like logs (these are text files)
    - There is so much space around everything in a report
    - For an example of how to make something like this look nice while still maintaining readability please look at how crashes look like in Xcode's Organizer window (or HockeyApp's crashlogs - but these were only easy to read and not looking that nice)
3. Thread names are not shown anymore (although the apple crash report delivers the names)
4. Dsym/build artefacts cannot be downloaded manually

This is not a complete list, though.

Please don't take this comment personally, it is not meant like that, though it is very difficult to describe missing features / things that you miss after using it for years without offending somebody.
But this is truly not the intent. 

We are all professionals and we like to work professionally.
Removing features, that are in use daily, from a product kills productivity and because I am not the only one who will experience that I simply want to give you the most honest feedback I can give.

You need to know what your users think, in order to make your products better and better.
I hope this helps and I ask you to take this feedback like a professional, because we all are in the same boat.

I really would like to stay with AppCenter if it doesn't take that long to have kinda feature-parity with HockeyApp.

**Comment by marcoburato** [comment]
Before you start working on #698 #458 , could you have a look at #1360 ?
If you think it's a good idea, it could help structure the code in a way that makes it easy to implement that ticket in the future.

**Comment by rishimodha** [comment]
Is it possible to get #1319 included in this plan?

**Comment by lbrownell-gpsw** [comment]
MacOS platform still shows as "preview" in the UI, when adding a new app.  Is that correct?  What's missing?  Does this impact transition from HockeyApp?

**Comment by Zee-day** [comment]
Can we get #32  in this one please?

**Comment by derpixeldan** [comment]
@lbrownell-gpsw with Sparkle support macOS is out of preview. No impact for the transition.

**Comment by andrewtremblay** [comment]
If possible, finer grain support for notifications (like https://github.com/microsoft/appcenter/issues/1118) would be enormously helpful for orgs that have a lot of applications building.

**Comment by lbrownell-gpsw** [comment]
> @lbrownell-gpsw with Sparkle support macOS is out of preview. No impact for the transition.

OK, so should probably change this: 
![image](https://user-images.githubusercontent.com/11181437/68876717-c4e0ba80-06b9-11ea-90c0-cab53feff0be.png)

**Comment by winnieli1** [comment]
Hi @Fab1n  - thanks for your helpful feedback! 

1) Cannot upload (Apple) crash reports manually - have you opened a support ticket? Our engineering and support team can take a closer look for you.
2) The crash log are really bad to read - absolutely, we have a list of things on our backlog to improve our UI.
3)Thread names are not shown anymore (although the apple crash report delivers the names) -  I beleive you're referring to this issue #857 ? Our team is working on this bug and it should be fixed very soon.
4) Dsym/build artefacts cannot be downloaded manually - do you mean in App Center Diagnostics? Or in our Build service? You can download your dsym files in Build and use our APIs too. 

I'm more than happy to hop on a call or start an email thread if you'd like to chat more. We really appreciate you taking the time to relay this feedback. Thanks!

**Comment by Fab1n** [comment]
> Hi @Fab1n - thanks for your helpful feedback!
> 
> 1. Cannot upload (Apple) crash reports manually - have you opened a support ticket? Our engineering and support team can take a closer look for you.

No, I didn't until now. The UI for manual uploading is simply missing. We need this. But I think you already have it on your list, but I don't know how much of a priority it is.
> 2. The crash log are really bad to read - absolutely, we have a list of things on our backlog to improve our UI.
>    3)Thread names are not shown anymore (although the apple crash report delivers the names) -  I beleive you're referring to this issue #857 ? Our team is working on this bug and it should be fixed very soon.

Awesome!
> 3. Dsym/build artefacts cannot be downloaded manually - do you mean in App Center Diagnostics? Or in our Build service? You can download your dsym files in Build and use our APIs too.

We don't build with AppCenter, we have a Jenkins instance and just upload the dsym files to AppCenter for each specific version.
If there is a macOS/iOS spindump, services like AppCenter/HockeyApp do not support symbolicating files like this.
These then need to be symbolicated locally. Therefor I need the symbol files for the exact build the spindump was created for. 
In Hockey we could just download the dSym stuff for the build and were good to go.
In Hockey there is a tab called 'symbols' where I can download stuff, but I don't see the versions that are included in the artifacts.

> I'm more than happy to hop on a call or start an email thread if you'd like to chat more. We really appreciate you taking the time to relay this feedback. Thanks!

Thanks for this option and your help! We'll better use that then.

**Comment by lacostej** [comment]
A little comment / request WRT automatically moving apps:

From: https://www.hockeyapp.net/blog/2019/11/16/hockeyApp-is-being-retired.html
> All HockeyApp user and organization accounts have already switched to App Center. For apps
> that haven’t been moved to App Center yet, we will start moving them over automatically. It will
> take us a few months to complete the move of all apps. During that time, you can still move apps
> manually by yourself.

Each of our apps builds for multiple platforms, Custom OS being one of them. The whole build/deployment system ties these related apps together.

So as of today, even for if a given product some apps could be moved, we are not proceeding because we are waiting for Custom OS to be available to move them.

If AppCenter was to start moving automatically our apps per platform, it will break our operations.

**Q: Is there a way to prevent this from happening?** *Once Custom OS is in place, we should be able to move rather quickly.*

Thanks

**Comment by derpixeldan** [comment]
@lacostej you don't need to do anything. We're not moving any of your apps. Custom OS support is coming soon, I'll update #464 once it's available.

**Comment by jbrozen** [comment]
> Dsym/build artefacts cannot be downloaded manually - do you mean in App Center Diagnostics? Or in our Build service? You can download your dsym files in Build and use our APIs too.

And we also do this:

> We don't build with AppCenter, we have a Jenkins instance and just upload the dsym files to AppCenter for each specific version.
If there is a macOS/iOS spindump, services like AppCenter/HockeyApp do not support symbolicating files like this.
These then need to be symbolicated locally. Therefor I need the symbol files for the exact build the spindump was created for.
In Hockey we could just download the dSym stuff for the build and were good to go.
In Hockey there is a tab called 'symbols' where I can download stuff, but I don't see the versions that are included in the artifacts.


We will also need these in the future. There's very little technical information around the build/releases exposed in AppCenter (like HockeyApp). Is there a gap analysis being done to ensure feature parity?

Thanks

**Comment by caisd1998** [comment]
Could you also add #1203  "IOS13 support with Appcenter using Appium 1.15"? Similar topic for iOS 13 test support.

**Comment by KS261187** [comment]
@caisd1998     I spoke to the App center support team to accelerate the upgrade but no luck as of now. They dont have anything planned up in the near future. 

@Oddj0b  we would like to understand the road map for the Appium upgrade which will help us to plan better.

Thanks
Krishnan

**Comment by lbrownell-gpsw** [comment]
December plan?

**Comment by Oddj0b** [comment]
December iteration plan is out #1494
