### ISSUE TITLE
Iteration Plan for December 2019

### ISSUE THREAD

**Issue by Oddj0b** [microsoft/appcenter#1494]
# December 2019 Plan

### Auth
- [ ] ~Support bringing your own identity management provider (Firebase Authentication and Auth0) with App Center Auth [#637]~
- [ ] ~Enable developers to connect their Active Azure Directory to Auth [#994]~

### Data
- [ ] ~Continue Free Tier investigatory work [#799]~
- [ ] ~Traffic Map in Metrics Explorer [#660]~
- [ ] ~Engineering Design Work on Data Change Notifications [#1121]~

### Diagnostics
- [x] Show unsymbolicated crashes and include in total counts [#110, #939 ]
- [x] Manually upload crash logs in the UI [#289, #1317]
- [x] Support deobfuscation for DexGuard [#220]

### Distribution
- [ ] ~Updated tester experience [#986, #140, #369, #1176]~

### General
- [x] Research for compute backend-as-a-service from App Center [#993]
- [x] Support Azure Active Directory security groups in App Center shared distribution groups

**Comment by easterapps** [comment]
Is there an iteration plan for January?

**Comment by dipree** [comment]
@easterapps going straight for February this time #1621

**Comment by lbrownell-gpsw** [comment]
https://github.com/microsoft/appcenter/issues still refers to December, which is still open.
