### ISSUE TITLE
Iteration Plan for April 2020

### ISSUE THREAD

**Issue by winnie** [microsoft/appcenter#1769]
# April 2020 Plan

Last month, the App Center team made some changes in the Diagnostics service to improve navigation and reduce the number of clicks needed to access relevant information. We added persistent filters, more details in the crash report view, and added a symbols management UI for Android and Windows apps. On the distribution side, we fixed few bugs and improved the overall experience of in-app update. Finally, engineering improvements were made to increase the reliability and scalability of our services. 

This month, we have the following features planned:

### API
- [ ] Introduce App-level API tokens [#167]

### Build
- [x] Update Android NDK version to support the latest version

### Test
- [x] Upgrade Appium support to version 1.17.x

### Distribution
- [x] Improve upload speed [Note: being rolled out gradually to all the customers using App Center Portal]
- [ ] Improve deep linking to release experience [#140]
- [x] Improve in-app update experience on Android [#1650]

### Diagnostics
- [ ] Improve symbol management experience
- [ ] Insights into versions affected by same crash group

### SDK
- [x] Support Sparkle EdDSA Signatures for Mac releases [#1410]
- [ ] Add support for Mac Catalyst* [#1578]

### Support
- [x] Switch customer support interface from bubble-chat style to email-based interaction

**Comment by nor0x** [comment]
any updates on https://github.com/microsoft/appcenter/issues/880 or https://github.com/microsoft/appcenter/issues/143 or https://github.com/microsoft/appcenter-sdk-dotnet/pull/658?

the feedback from the community is pretty clear - Xamarin.Mac support would help us a lot.

**Comment by phatmann** [comment]
Many of the top-requested features have been sitting there for months. Some of them are causing a lot of pain (e.g. #125) yet would take very little engineering time to implement. Is there a reason they keep getting deferred?

**Comment by ahdbilal** [comment]
@phatmann Thanks for the feedback. I will escalate this internally and will share an update soon.

**Comment by jonathanantoine** [comment]
@ahdbilal  pleas please include #125

**Comment by winnie** [comment]
@nor0x unfortunately no updates on Xamarin macOS support. We will continuously evaluate this in our planning.

**Comment by cschembor-ww** [comment]
Any updates regarding #159?

**Comment by EatonZ** [comment]
Would love to see https://github.com/microsoft/appcenter/issues/1313

**Comment by KeithBoynton** [comment]
@winnie Can you please share the rationale of why macOS is not getting the focus a lot of the community require?
