### ISSUE TITLE
Iteration Plan for May 2020

### ISSUE THREAD

**Issue by ahdbilal** [microsoft/appcenter#1837]
# May 2020 Plan

Last month, the App Center team updated various frameworks across our services (Android NDK, Appium, Sparkle) to support the latest versions of each respective framework. The team also made structural changes with our distribution upload client, as a result of which we expect users to get improved and reliable upload speed performance. The improved service will be rolled out to all users this month.  

This month, we have the following features planned:

### API
- [x] Introduce App-level API tokens [#167]

### Distribution
- [x] Roll out improved upload speed capability to all App Center portal users
- [ ] ~~Improve deep linking to release experience [#140]~~

### SDK
- [x] Package iOS SDK as SPM [#1295]
- [ ] Add support for Mac Catalyst [#1578]

**Comment by phatmann** [comment]
Could we please get #125 into this iteration? It is seriously hurting our workflow, and will not take long to implement. Thanks!

**Comment by ahdbilal** [comment]
Thanks @phatmann for the feedback. I have just pushed for it internally and will share an update soon.

**Comment by jasmsu** [comment]
Was "Insights into versions affected by same crash group" that was a part of the April 2020 plan dropped? Looks like it wasn't marked as done in April.

**Comment by imWildCat** [comment]
Anything which the community can help to support mac Catalyst?

**Comment by tdekoning** [comment]
@ahdbilal any update on ticket #125 being in this iteration plan?

**Comment by phatmann** [comment]
Could the dev team provide some insight into how issues are chosen for an iteration? Many top-rated issues are ignored month and month, while others are addressed much sooner. What is the criterion for selection? I for one have become increasingly frustrated with the lack of progress on fundamental aspects of App Center and wonder if this is just how it will be indefinitely.

**Comment by phatmann** [comment]
To provide a little more data, the majority of the most-commented issues are well over a year old.

**Comment by zoontek** [comment]
Could you take https://github.com/microsoft/appcenter/issues/1575 as well? Currently, the module is unusable with Error Boundaries and graceful crashes.

It would be super useful to catch unhandled Promise rejection (by overriding https://github.com/facebook/react-native/blob/0.63-stable/Libraries/Promise.js#L19) and custom non-fatal error too (by overriding `ErrorUtils` global handler)!

**Comment by Mikilll94** [comment]
Any update on #125 (Google Play internal test track support)?

**Comment by zoontek** [comment]
This project is dead 💀

**Comment by ahdbilal** [comment]
Thanks all for raising these issues. I agree that customer-facing features (#125 especially) have suffered over the last few months. The team has been focused on improving the backend and stabilizing the service during this time. We need to do a better job of providing more clarity on how we are prioritizing our work. I have taken a note of it and shared this as well as your other concerns with the leadership. We will sync back with you soon to share more details of the road forward.

**Comment by joshfriend** [comment]
Many folks are frustrated because we have used this product for a long time now, by which I mean HockeyApp (which Microsoft acquired and transitioned to appcenter). There were features which HockeyApp _already had_ which were _removed_ when we were forced to transition to AppCenter as HockeyApp was completely shutdown (e.g. linking to specific builds which is still a huge pain point for everyone). Additionally, HockeyApp had very popular feature requests that we had been pressuring to add for years which were seemingly deprioritized by a LOT (caught exceptions for example) after the AppCenter transition in favor of features which we hadn't really been asking for as much.

I fully understand that you have backend work to do, as an outsider i have no idea what kind of issues you may have been left with as a result of the hockeyapp sunsetting! I just wanted to add my perspective (which I think I have seen reflected in other comments on various issues) that long time users of HockeyApp (RIP) are frustrated by what we were familiar with as a _very good_ app distribution and crash reporting tool being turned into a much larger platform which actually does not do as good of a job at performing the duties that HockeyApp used to.

I follow a lot of the issues and feature requests here and lately it has become difficult to tell if there will be meaningful changes made anytime in the near-ish future regarding the features which my team considers important.

I know yall do try pretty hard to respond to issues, and appcenter is still the best distribution platform for test builds that I have found. ❤️

**Comment by yvbeek** [comment]
@ahdbilal Thank you, I see you've updated the Roadmap document:
https://github.com/Microsoft/appcenter/wiki/Roadmap

What would be the best way for us to keep track of the updates that are being done to the App Center platform?

I think that many of us are worried that App Center is moved to the back burner and that eventually Microsoft will shutdown the platform. I'm not sure if you can share any further details, like how many people are actively working on it. The platform has a few quirks and might have some overlap with GitHub actions, but it would be great if we could continue to use it over the years to come.

**Comment by danielwilson1702** [comment]
It is not sounding great tbh. Tech debt doesn't really wash with me this project is not that old and crying out for more features, so why put _everyone_ on solving tech debt? Also mid-2021 is oddly specific and an enormous time frame to solve all this tech debt :/
