### ISSUE TITLE
Iteration Plan for April 2019

### ISSUE THREAD

**Issue by patniko** [Microsoft/appcenter#227]
# April 2019 Plan 
Last month we landed the majority of our major workload, but are finishing up one carry over user request. A major release date for us always falls around the time of our Build conference early May so we'll be hunkering down this month and focusing on hitting our preview release goal for the new Identity and Storage service along with the initial version of the HockeyApp migration experience.

We recently updated the roadmap to include even more details on the future. You'll start seeing more public specifications from our team around highly requested support such as the [Windows spec](https://github.com/Microsoft/appcenter/pull/193) recently opened up by @winnieli1208. We encourage you to participate and share your experiences so we can build the best solutions possible.

We've recognized a big demand for improvements to our Build service and are committed to addressing some of these needs. Along with the currently open [spec for cloning branch configurations](https://github.com/Microsoft/appcenter/pull/254) you'll see some other plans for improvements trickle out over the coming months.

### Build
- [x] Support for building apps with Xcode 10.2 on macOS Mojave. All builds using Xcode 9.4.1 or above will begin building on macOS Mojave [#264]
- [x] Support for building apps with Mono 5.18, Xamarin.iOS 12.6, Xamarin.Android 9.2, and Xamarin.Mac 5.6 [#187]

### Data
- [x] Configure new Cosmos DB database in App Center [#270]
- [ ] ~~Connect existing Cosmos DB database in App Center~~ [#271]
- [ ] ~~View Utilization Metrics~~ [#272]
- [x] Create the "Getting Started" page for the Data service [#273]

### Diagnostics
- [ ] ~~Filter crash and error groups by build number~~ [#133]
- [x] Search for handled errors [#269]

### Distribution
- [x] Disable in-app update when in guided access mode [#46] (@florianbuerger)
- [ ] ~CodePush support for Electron apps~

### General
- [ ] ~~Add support to indicate the environment or release type of an app~~ [#120]

### Identity
- [ ] ~~Create a new AD B2C directory in App Center~~ [#113]
- [ ] ~~Manage AD B2C custom policies~~ [#246]
- [ ] ~~View and search the list of users who have authenticated~~ [#247]
- [x] Create the "Getting Started" page for Identity [#248]

### Push
- [x] Publish Push to User API [#256]
- [x] Publish Push to User UI [#257]

### Test
- [x] NUnit 3 support [#123]

### SDK
- [x] Drop support for Xcode 8 and 9 [#308]

**Comment by toomasz** [comment]
Could you add support for xamarin Android 9.2 to this interation plan?

https://github.com/Microsoft/appcenter/issues/187

**Comment by nrajpurkar** [comment]
@toomasz definitely on our plans for this month. Adding it to the iteration plan

**Comment by myokeeh** [comment]
So more support for UWP, right?

**Comment by bernardoflynn** [comment]
Is there any update on the Apple ID issue? I can't use 2FA when connecting my company Apple ID. The 2FA code I get is always wrong and each time I put in the 'wrong' one I get another one that also doesn't work <loop indefinitely>

**Comment by SnidelyWhiplash** [comment]
> Is there any update on the Apple ID issue? I can't use 2FA when connecting my company Apple ID. The 2FA code I get is always wrong and each time I put in the 'wrong' one I get another one that also doesn't work

@bernardoflynn Be sure to note the difference between the 2FA and the app-specific key. I'd start by _disconnecting_ your apple account from your App Center account settings -> Developer accounts tab.

**Comment by devandanger** [comment]
Could you elaborate on what Enterprise AAD support means?  We currently are using AAD for Azure Devops for some of our enterprise's apps.  We are transitioning additional off of TFS and are looking at some AppCenter capabilities maybe in Q3.
