### ISSUE TITLE
Iteration Plan for June 2019

### ISSUE THREAD

**Issue by blparr** [microsoft/appcenter#466]
# June 2019 Plan 
May has been an exciting month!

We have shipped our first MBaaS services as early public previews for **Auth** [#388] and **Data**. Note that we are still planning to iterate on new features and improvements. Give it a try and let us know what you think!

We are continuously listening to your feedback, so have decided to invest in our **Build** service, shipping clone branch configurations [#22] and starting an investigation on gitlab.com and general git support [#37]. Our team has also started work on supporting WPF and WinForms apps for diagnostics, analytics, and distribution [#367][#53]. 

Last but not least, we are also now offering a private preview for **HockeyApp** users to smoothly migrate to Visual Studio App Center. Please reach out if you would like to be part of this preview.

### Analytics
- [ ] Support analytics for WPF/WinForms apps

### Auth 
- [x] Expose JSON web token (JWT), raw claims, standard and custom properties [#393]
- [x] Address multiple user issues while configuring Auth [#474]

### Build
- [x] Allow download of Proguard mapping.txt file after a build [#130]
- [x] Forward Proguard mapping.txt file to Diagnostics after a build [#169]
- [ ] Support building apps with the Kotlin DSL [#38]
- [ ] Begin GitLab.com support [#37]
- [ ] Support for building iOS apps with Xcode 11 beta [#517]
- [x] Support selecting a NodeJS version for React Native apps [#507]

### Data
- [x] Add Remote Operation listeners to Native iOS and Xamarin iOS SDKs [#475]
- [x] Address multiple user issues while configuring Data [#476]

### Diagnostics
- [x] Filter crash and error groups by build number [#133]
- [ ] Support crashes and errors for WPF/WinForm apps

### Distribution
- [ ] Fix in-app updates login for HockeyApp apps using App Center SDK

### General
- [x] Finalize adding a Member role to Organizations
- [x] Increase the number of API tokens from 200 to 5000
- [ ] Finalize AAD groups support in Organizations

### Push
- [x] A short Push Survey [#491]

**Comment by lacostej** [comment]
#461 is a blocker for us under *HockeyApp Migration Experience* and *Distribution*

**Comment by mike14u** [comment]
#65 will help us greatly improve our pipelines, hopefully we can have it as well.

**Comment by nrajpurkar** [comment]
@mike14u definitely something we will continue to look into for future work

**Comment by philihp** [comment]
any chance we could fit #161 in before Q3?

**Comment by nrajpurkar** [comment]
@philihp not in the plans for June unfortunately. We'll keep looking into that work for later iteration plans.

**Comment by toomasz** [comment]
@blparr 
Could you add support for xamarin android 9.3? https://github.com/microsoft/appcenter/issues/534

**Comment by nrajpurkar** [comment]
@toomasz Take a look at the response directly at #534

**Comment by jacobg** [comment]
Sadly, Code Push seems to be sorely neglected:
https://github.com/microsoft/cordova-plugin-code-push/issues/530#issuecomment-497131461
https://github.com/microsoft/cordova-plugin-code-push/pull/513#issuecomment-489084701

**Comment by josecaodaglio** [comment]
@blparr unfortunately @jacobg  is correct. We are dealing with a problem that should be very straightforward to check but we are being neglected.

**Comment by botatoes** [comment]
@jacobg @josecaodaglio Thanks for pointing those out. We know we've haven't been giving CodePush lots of love lately but we are actively making an effort to change that. Over the next few months, we'll be working on some core improvements and updates to the CodePush service. The work will allow us to support and improve CodePush in the future. However, this means we are pulling the people who have been working on support to work on this improvement. Please bear with us for a bit while we give CodePush some love. 

The messaging I've put out today is the following. You will see these on the CodePush readmes: 
> Over the next few months, we will be working on a new version of CodePush that will address some of the most common performance issues our customers are facing. This updated version will allow a better experience, our team to better support CodePush moving forward and have a faster development cycle for new features. 
We are prioritizing this work because we believe this to be the most valuable thing we can do for our CodePush customers in the long run. Starting June 11th 2019, support will slow down, bug fixes will be limited to critical bugs, and new feature development will pause until we finish this core update.

**Comment by josecaodaglio** [comment]
@botatoes thank you for your answer. I am glad you are willing to give the code-push the attention he deserves, as it supports a lot of critical applications.

Although you mentioned that the support _will slow down from tomorrow_, this issue has started since a while now. As far as I could understand, @jacobg , @dann95 and myself have same problem in the thread https://github.com/microsoft/cordova-plugin-code-push and should be very simple to replicate it, as at least in my case, it happens 100% of the time and I can send you controlled credentials so you can check for yourself. Maybe this is important for the next version as well.

**Comment by poldz123** [comment]
I guess no one has taken action to this issue: https://github.com/microsoft/appcenter-sdk-android/issues/933

**Comment by winnieli1208** [comment]
Hi @poldz123 - due to other priorities at the moment, we don't have any immediate plans to bring handled exceptions to Android apps. This is something we absolutely hope to implement in the future and I encourage you to give this [feature request](https://github.com/microsoft/appcenter/issues/432) a +1 to help our team prioritize this. Thanks!

**Comment by poldz123** [comment]
@winnieli1208 - I would love to +1 but most of the people are redirected to the android repo instead of the main repo for the SDK. Which resulted in more +1s to the android repo. I hope devs are looking to that page.

**Comment by winnieli1208** [comment]
@poldz123 absolutely! We are monitoring all SDK repos as well as this one 👀

**Comment by bennoffsinger** [comment]
When will ACP - App Center Push be released as it is now only in preview?

**Comment by jwargo** [comment]
@bennoffsinger good question, it's pretty much feature complete, so not a lot is going to change before we GA except for one thing that we're still sorting out. Do you have time to chat with me about your app and your requirements?  I can help you understand the impact of GA on your app. just send me an email at first dot last at you know what dot com. :-)

**Comment by bennoffsinger** [comment]
I would be happy to chat.
