### ISSUE TITLE
Iteration Plan for July 2019

### ISSUE THREAD

**Issue by winnieli1** [microsoft/appcenter#634]
# July 2019 Plan

Last month, we made major improvements and fixes to Auth. We shipped support for React Native and added support to expose the JSON Web Token to allow for quicker integration with other Azure services. We also improved the user experience in the portal, including the ability to create Azure resources directly from Auth.

You'll also notice additions in various parts of our products. Our Build service now allows you to select a NodeJS version in your build settings, makes your ProGuard mapping files available for download and automatically forwards these files to our Diagnostics service if you have the SDK module enabled. In the Diagnostics service, we've added a Build filter in our Diagnostics page so you can find the relevant crashes you want by app version _and_ build. Finally, drawing some inspiration from HockeyApp, we added a new Member role so you can better manage your organization and permissions.

June was a busy start of the summer season and we're incredibly excited for the work we have planned in July.  Our Build service will continue to get some attention as we are committed to addressing some of the feedback we've heard from the community. We also expect to make some improvements in areas like our Data and Distribution service.

Last but not least, expect to see some exciting announcements this month regarding our support for WPF and WinForms applications. Since June, our team has been working hard to bring distribution, analytics, and crash repointing support for your WPF and WinForms desktop applications. Stay tuned for our release this month!

### Analytics
- [ ] ~Support analytics for WPF/WinForms apps [#118]~

### Auth
- [x] Support bringing your own identity management provider with App Center Auth [#637]
 
### Build
- [x] GitLab.com support [#37]
- [x] Support for building iOS apps with Xcode 11 beta [#517]

### Data
- [x] Offline list support  [#659]
- [x] Update default offline persistence from 1 day to infinite [#661]
- [ ] ~Metrics Explorer [#660]~

### Diagnostics
- [ ] ~Support crashes and errors for WPF/WinForm apps [#367][#118]~
- [ ] ~API to upload custom crashes [#31]~

### Distribution
- [ ] ~Fix in-app updates login for HockeyApp apps using App Center SDK~

### General
- [ ] ~Finalize AAD groups support in Organizations~

### Push
- [x] A short Push Survey [#491]

**Comment by LaloCo** [comment]
I was really hoping this would include #398 😢

**Comment by mike14u** [comment]
What happened to #169 it was included on the last iteration and had a check (means done right?). But it isn't really working at all when we already have built + deployed and the ticket is still open?

**Comment by nrajpurkar** [comment]
@mike14u we added this in last month, you're correct this is done. Android builds now generate the Proguard mappings. Please reach out to support if you're having issues with this feature so we can better understand what is going on. Thanks!

**Comment by jcmarcfloress** [comment]
Thank you

**Comment by skywalkerlol** [comment]
Really hoping #30 was in the July plan. Oh well, maybe the next one.

**Comment by PvanHengel** [comment]
When will the AAD support be done and documented?  We are having a very hard time getting our Azure Business users access to appcenter.
