### ISSUE TITLE
Iteration Plan for August 2019 

### ISSUE THREAD

**Issue by patniko** [microsoft/appcenter#792]
# August 2019 Plan

Last month proved that beta's don't take vacations as we raced to keep up to date with iOS beta support for build. On the new service front we shored up our Data service by providing full offline list support and fighting the "tyranny of the default" with a new default offline persistence setting of "infinite." We also began work on our BYOI story which we hope to complete this month. Lastly, we delivered much requested support for the online version of GitLab. 

This month we intend to bring support for private, on premise GitLab instances to build, as well as AAB bundle support for Xamarin.Android apps and Mono 6.0 support. Diagnostics will get some iOS extensions attention, the ability to upload custom crashes, and some needed UWP support. BYOI efforts will continue for Auth, as will investigatory work on a free tier for Auth and Data services. Take a look at our Data Metrics Explorer feature if you get a chance; we are pretty excited about it.

### Analytics
- [x] Support analytics for WPF/WinForms apps [#118]

### Auth
- [ ] ~Support bringing your own identity management provider with App Center Auth [#637]~
- [ ] ~Customer development study on a Free Tier for App Center Auth [#794]~

### Build
- [ ] ~Self-Hosted GitLab Support [#37]~
- [x] Support for building apps with Mono 6.0, Xamarin.iOS 12.14 with preview support for Xcode 11, Xamarin.Android 9.4, and Xamarin.Mac 5.14 [#632, #796, #769]
- [x] Android App Bundle Support for Xamarin.Android apps [#194]

### Data
- [ ] ~Data Metrics Explorer [#660]~
- [ ] ~Investigatory work on Free Tier for App Center Data [#799]~
- [ ] ~Investigatory work on Data Explorer [#800]~

### Diagnostics
- [ ] ~API to upload custom crashes [#31]~
- [ ] ~Support iOS extensions [#687]~
- [x] Support crashes and errors for WPF/WinForm apps {#367][#118]
- [ ] ~Crashes and errors support for UWP apps [#752, #150, #403]~

### Distribution
- [ ] ~In-app update through public distribution groups [#182]~
- [ ] ~macOS in-app update [#202]~
- [x] Fix iPhone XS install profile [#615] 
- [x] Automatically distribute Android App Bundles after building in App Center [#194]

### SDK
- [x] Add an equivalent function for "didReceiveMemoryWarningInLastSession" [#199]
- [x] .NET Core 3 support for analytics and diagnostics [#53]

### General
- [x] Dark Mode Preview

**Comment by Zee-day** [comment]
Are there any plans to bring issue #32 into this iteration?

**Comment by sgreifeneder** [comment]
And of course #30, which is out there for some time now.

**Comment by nrajpurkar** [comment]
@sgreifeneder working on #796. We've got other priorities in-flight for new features in Build, but we'll be taking another look at #30 soon.

@Zee-day unfortunately we don't have bandwidth to pick up #32 this month, but I hear you and we'll be keeping that one top-of-mind for future iteration plans.

**Comment by msioen** [comment]
With regards to #194 which is already mentioned in the main issue. Can distribution (or at least some 'availability') of aab files also be taken up? Just for download, not necessarily for install.

Currently you can upload .aab files with the rest api but the distribute fails. Because of this the release isn't listed.
We don't automate our store uploads yet but would still like to have these aab files available for manual download.

**Comment by tpgmeligmeyling** [comment]
Any plans which iteration will contain microsoft/appcenter-sdk-apple#1226?

**Comment by claitonlovato** [comment]
Please consider #30 !!! Its very important for migrating our builds to AppCenter ;)

**Comment by tonylambert** [comment]
Please consider upload .dmg support for macOS and “custom” .exe/.zip for Windows on the distribution front for August. Not supporting these formats is a barrier to our migration from HockeyApp to AppCenter.

**Comment by derpixeldan** [comment]
@tpgmeligmeyling likely next months SDK release.

**Comment by rudyrichter** [comment]
https://github.com/microsoft/appcenter-sdk-apple/issues/1270 is a blocker for my team's transition to AppCenter.

**Comment by adamKasapakis** [comment]
What is the progress with #182, is it going to be fixed in August? 
It's a big blocker for us and it needs to be fixed before we migrate to app center.

**Comment by kvpt** [comment]
We also need #182, it's critical for us to be able to migrate to AppCenter and HockeyApp shutdown in  less than 100 days. 😱

**Comment by botatoes** [comment]
@adamKasapakis @kvpt we are actively working on #182. My fault for not adding it to the iteration plan. Very sorry 😭

**Comment by adamKasapakis** [comment]
@botatoes Thank you for updating the iteration, should we expect it in August then?

**Comment by meliheran** [comment]
[#30](https://github.com/microsoft/appcenter/issues/30) please

**Comment by derpixeldan** [comment]
@adamKasapakis we might finish the work this month but the SDK release will be next month.

**Comment by brminnick** [comment]
Re #632, #796, #769:

Builds using .NET Core 3.0 are still failing, despite updating to the Latest Stable build agent, Mono v6.0, because App Center Build is using .NET Core 2.2 to restore NuGet Packages.

<img width="576" alt="Screen Shot 2019-08-16 at 2 04 39 PM" src="https://user-images.githubusercontent.com/13558917/63198228-e4226a00-c02e-11e9-8243-5502dae27dfa.png">


## Recommended Fix

App Center Build should update the `Restore Nuget` step to use .NET Core 3. 

.NET Core 3 is backwards compatible with all versions of .NET Core, and [.NET Core 3.0 Preview 8 is recommended for production by the .NET Core Team](https://devblogs.microsoft.com/dotnet/announcing-net-core-3-0-preview-8/?WT.mc_id=dotnet-reddit-bramin):

> NET Core 3.0 Preview 8 is supported by Microsoft and can be used in production

## Error 

> ##[section]Starting: Restore Nuget
> ==============================================================================
> Task         : Command Line
> Description  : Run a command line with arguments
> Version      : 1.1.3
> Author       : Microsoft Corporation
> Help         : [More Information](https://go.microsoft.com/fwlink/?LinkID=613735)
> ==============================================================================
> [command]/bin/bash -c /usr/bin/find . -name '*.sln' -type f -print0 | /usr/bin/xargs -0 grep -l 'MondayPundayApp.Droid.csproj' | /usr/bin/xargs -I '{}' nuget restore '{}' -DisableParallelProcessing
MSBuild auto-detection: using msbuild version '15.0' from '/Library/Frameworks/Mono.framework/Versions/6.0.0/lib/mono/msbuild/15.0/bin'.
/Users/vsts/agent/2.155.1/work/1/s/Src/MondayPundayApp.UWP/MondayPundayApp.UWP.csproj : error MSB4057: The target "_IsProjectRestoreSupported" does not exist in the project.
/var/folders/24/8k48jl6d249_n_qfxwsl6xvm0000gn/T/NuGetScratch/j0qwi7cl.9qh.nugetrestore.targets(290,5): warning : Skipping restore for project '/Users/vsts/agent/2.155.1/work/1/s/Src/MondayPundayApp.UWP/MondayPundayApp.UWP.csproj'. The project file may be invalid or missing targets required for restore. [/var/folders/24/8k48jl6d249_n_qfxwsl6xvm0000gn/T/NuGetScratch/ty2q14ca.lvq.nugetinputs.targets]
/Users/vsts/hostedtoolcache/dotnet/sdk/2.2.300/Sdks/Microsoft.NET.Sdk/targets/Microsoft.NET.TargetFrameworkInference.targets(137,5): error NETSDK1045: The current .NET SDK does not support targeting .NET Core 3.0.  Either target .NET Core 2.2 or lower, or use a version of the .NET SDK that supports .NET Core 3.0. [/Users/vsts/agent/2.155.1/work/1/s/Src/MondayPundayApp.UnitTests/MondayPundayApp.UnitTests.csproj]
>
> ##[error]/bin/bash failed with return code: 1
> ##[error]/bin/bash failed with error: /bin/bash failed with return code: 1

**Comment by Lukas34** [comment]
#845 would be nice.

**Comment by patniko** [comment]
#30 should be coming in the next iteration @meliheran!

**Comment by msdof** [comment]
#458 should be considered into next iteration, R8 is the default code shrinker for Android.
